### ISSUE TITLE
You dont check thing

### ISSUE THREAD

**Issue by NekOware** [casualdegenerate/rblx#2]
https://github.com/casualdegenerate/rblx/blob/b04b6f13312c38ce538286eb3c29cf0578ae13bb/Auto%20Exec/Main.lua#L62

this thing no check if `cd` folder exist. script bad.

**Comment by casualdegenerate** [comment]
The project repo has been archived, please refer to my patch at https://github.com/casualdegenerate/patch/blob/main/ags/Main.lua or fork it to patch yourself your own. <3
